name: MusicTrivia

on:
  push:
    branches:
      - feature-security-test
    
  pull_request:
   types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'
        
    - name: Build with Gradle
      run: |
        cd MusicTrivia
        chmod +x gradlew
        ./gradlew assemble --no-daemon

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'

    - name: Test with Gradle
      run: |
        cd MusicTrivia
        chmod +x gradlew
        ./gradlew test

  sonarqube:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'

    - name: Build with Gradle
      run: |
        cd MusicTrivia
        chmod +x gradlew
        ./gradlew assemble --no-daemon

    - name: Sonarqube scan
      run: |
        cd MusicTrivia
        chmod +x gradlew
        ./gradlew sonar
        
  owasp-zap:
    runs-on: ubuntu-latest
    needs: sonarqube

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'

    - name: Build with Gradle
      run: |
        cd MusicTrivia
        chmod +x gradlew
        ./gradlew assemble --no-daemon

    - name: Start the application
      run: |
        cd MusicTrivia
        chmod +x gradlew
        ./gradlew bootRun &
      continue-on-error: true

    - name: Prepare ZAP Config
      run: |
        mkdir -p .zap
        echo "configurations..." > .zap/zap.yaml
        chmod 644 .zap/zap.yaml

    - name: Run OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.12.0
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:8080/songs'
          rules_file_name: '.zap/zap.yaml'
          cmd_options: '-a'
          
    - name: Upload ZAP Report
      uses: actions/upload-artifact@v2
      with:
        name: zap-report
        path: owasp-zap-report.html
     
  docker:
    runs-on: ubuntu-latest
    needs: owasp-zap

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'

    - name: Build with Gradle
      run: |
        cd MusicTrivia
        chmod +x gradlew
        ./gradlew assemble --no-daemon

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        cd MusicTrivia
        docker build -t tonyj3/music-trivia-backend:latest .
        docker push tonyj3/music-trivia-backend:latest
