name: MusicTrivia

on:
  push:
    branches:
      - feature-song-function

jobs:
 build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'
    - run: |
        cd MusicTrivia
        ./gradlew build --no-daemon

    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: Grant execute permission to Gradle wrapper script
      run:  |
        cd MusicTrivia
        chmod +x gradlew
    - name: Build with Gradle
      run:  |
        cd MusicTrivia
        ./gradlew assemble

    - name: Test with Gradle
      run: ./gradlew test
