name: MusicTrivia

on:
  push:
    branches:
      - feature-song-function

jobs:
 build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Grant execute permission to Gradle wrapper script
      run: chmod +x MusicTrivia/gradlew

    - name: Build with Gradle
      run: |
        cd MusicTrivia
        ./gradlew assemble

    - name: Test with Gradle
      run: |
        cd MusicTrivia
        ./gradlew test
