name: MusicTrivia

on:
  push:
    branches:
      - feature-song-function

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'
        
    - name: Build with Gradle
      run: |
        cd MusicTrivia
        chmod +x gradlew
        ./gradlew assemble --no-daemon

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'

    - name: Test with Gradle
      run: |
        cd MusicTrivia
        chmod +x gradlew
        ./gradlew test
     
