name: MusicTrivia

on:
  push:
    branches:
      - feature-song-function

jobs:
 build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install JDK 21
      run: |
        sudo apt update
        sudo apt install -y openjdk-17-jdk
        sudo update-java-alternatives --set java-1.17.0-openjdk-amd64
        java -version
        
    - name: Change directory to MusicTrivia
      run: cd MusicTrivia

    - name: Build with Gradle
      run: ./gradlew assemble

    - name: Test with Gradle
      run: ./gradlew test
