name: MusicTrivia

on:
  push:
    branches:
      - feature-song-function

jobs:
 build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Change directory to MusicTrivia
      run: cd MusicTrivia

    - name: Build with Gradle
      run: ./gradlew assemble

    - name: Test with Gradle
      run: ./gradlew test
