name: MusicTrivia

on:
  push:
    branches:
      - feature-song-function

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'
        
    - name: Build with Gradle
      run: |
        cd MusicTrivia
        chmod +x gradlew
        ./gradlew assemble --no-daemon

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'

    - name: Test with Gradle
      run: |
        cd MusicTrivia
        chmod +x gradlew
        ./gradlew test
     
  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        cd MusicTrivia
        docker buildx build --platform linux/amd64,linux/arm64 -t tonyj3/music-trivia-backend:$GITHUB_SHA .
        docker push tonyj3/music-trivia-backend:$GITHUB_SHA
    
